using System.IO;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Media;
using HospitalityPOS.Core.Enums;
using HospitalityPOS.Core.Interfaces;
using HospitalityPOS.Core.Models.Reports;
using Serilog;

namespace HospitalityPOS.WPF.Services;

/// <summary>
/// Service for printing sales reports to thermal or standard printers.
/// </summary>
public class ReportPrintService : IReportPrintService
{
    private readonly ILogger _logger;
    private const int LineWidth = 48; // 80mm thermal printer character width

    /// <summary>
    /// Initializes a new instance of the <see cref="ReportPrintService"/> class.
    /// </summary>
    /// <param name="logger">The logger.</param>
    public ReportPrintService(ILogger logger)
    {
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    /// <inheritdoc />
    public bool PrintSalesReport(SalesReportResult report)
    {
        if (report == null)
        {
            throw new ArgumentNullException(nameof(report));
        }

        try
        {
            var printContent = GeneratePrintContent(report);

            // Create a FlowDocument for printing
            var document = new FlowDocument
            {
                FontFamily = new FontFamily("Consolas"),
                FontSize = 10,
                PageWidth = 280, // ~80mm at 96 DPI
                PagePadding = new Thickness(10),
                ColumnWidth = 280
            };

            // Split content into lines and add paragraphs
            var lines = printContent.Split('\n');
            foreach (var line in lines)
            {
                var paragraph = new Paragraph(new Run(line))
                {
                    Margin = new Thickness(0, 0, 0, 0),
                    LineHeight = 1
                };
                document.Blocks.Add(paragraph);
            }

            // Show print dialog
            var printDialog = new PrintDialog();
            if (printDialog.ShowDialog() == true)
            {
                var paginator = ((IDocumentPaginatorSource)document).DocumentPaginator;
                printDialog.PrintDocument(paginator, "Sales Report");
                _logger.Information("Sales report printed successfully");
                return true;
            }

            _logger.Information("Print dialog cancelled by user");
            return false;
        }
        catch (Exception ex)
        {
            _logger.Error(ex, "Failed to print sales report");
            throw;
        }
    }

    /// <inheritdoc />
    public string GeneratePrintContent(SalesReportResult report)
    {
        var sb = new StringBuilder();

        // Header
        sb.AppendLine(new string('=', LineWidth));
        sb.AppendLine(CenterText("SALES REPORT", LineWidth));
        sb.AppendLine(new string('=', LineWidth));

        // Report Info
        sb.AppendLine($"From: {report.Parameters.StartDate:yyyy-MM-dd}");
        sb.AppendLine($"To:   {report.Parameters.EndDate:yyyy-MM-dd}");
        sb.AppendLine($"Generated: {report.GeneratedAt.ToLocalTime():yyyy-MM-dd HH:mm}");
        sb.AppendLine($"Generated by: {report.GeneratedBy}");
        sb.AppendLine(new string('-', LineWidth));

        // Sales Summary (always included)
        AppendSummarySection(sb, report.Summary);

        // Product Sales
        if (report.ProductSales.Count > 0)
        {
            sb.AppendLine(new string('-', LineWidth));
            AppendProductSalesSection(sb, report.ProductSales);
        }

        // Category Sales
        if (report.CategorySales.Count > 0)
        {
            sb.AppendLine(new string('-', LineWidth));
            AppendCategorySalesSection(sb, report.CategorySales);
        }

        // Cashier Sales
        if (report.CashierSales.Count > 0)
        {
            sb.AppendLine(new string('-', LineWidth));
            AppendCashierSalesSection(sb, report.CashierSales);
        }

        // Payment Method Sales
        if (report.PaymentMethodSales.Count > 0)
        {
            sb.AppendLine(new string('-', LineWidth));
            AppendPaymentMethodSection(sb, report.PaymentMethodSales);
        }

        // Hourly Sales
        if (report.HourlySales.Count > 0)
        {
            sb.AppendLine(new string('-', LineWidth));
            AppendHourlySalesSection(sb, report.HourlySales);
        }

        // Footer
        sb.AppendLine(new string('=', LineWidth));
        sb.AppendLine(CenterText("** END OF REPORT **", LineWidth));
        sb.AppendLine(new string('=', LineWidth));

        return sb.ToString();
    }

    private void AppendSummarySection(StringBuilder sb, DailySalesSummary summary)
    {
        sb.AppendLine("SALES SUMMARY");
        sb.AppendLine(new string('-', LineWidth));
        sb.AppendLine(FormatLine("Gross Sales:", $"KSh {summary.GrossSales:N2}"));
        sb.AppendLine(FormatLine("Discounts:", $"-KSh {summary.Discounts:N2}"));
        sb.AppendLine(FormatLine("Net Sales:", $"KSh {summary.NetSales:N2}"));
        sb.AppendLine(FormatLine("Tax Collected:", $"KSh {summary.TaxCollected:N2}"));
        sb.AppendLine(new string(' ', LineWidth - 20) + new string('-', 20));
        sb.AppendLine(FormatLine("TOTAL REVENUE:", $"KSh {summary.TotalRevenue:N2}"));
        sb.AppendLine();
        sb.AppendLine($"Transactions: {summary.TransactionCount}");
        sb.AppendLine($"Average Transaction: KSh {summary.AverageTransaction:N2}");
        if (summary.LargestTransaction > 0)
        {
            sb.AppendLine($"Largest Transaction: KSh {summary.LargestTransaction:N2}");
        }
        if (summary.VoidedCount > 0)
        {
            sb.AppendLine();
            sb.AppendLine($"Voided Transactions: {summary.VoidedCount}");
            sb.AppendLine($"Voided Amount: KSh {summary.VoidedAmount:N2}");
        }
    }

    private void AppendProductSalesSection(StringBuilder sb, List<ProductSalesReport> products)
    {
        sb.AppendLine("SALES BY PRODUCT");
        sb.AppendLine(new string('-', LineWidth));

        foreach (var product in products.Take(20)) // Limit to top 20 products
        {
            var name = product.ProductName.Length > 20
                ? product.ProductName[..17] + "..."
                : product.ProductName;
            sb.AppendLine($"{name}");
            sb.AppendLine($"  Qty: {product.QuantitySold:N0}  Net: KSh {product.NetSales:N2} ({product.Percentage:N1}%)");
        }

        if (products.Count > 20)
        {
            sb.AppendLine($"... and {products.Count - 20} more products");
        }

        var totalNet = products.Sum(p => p.NetSales);
        var totalProfit = products.Sum(p => p.GrossProfit);
        sb.AppendLine();
        sb.AppendLine(FormatLine("Total Net Sales:", $"KSh {totalNet:N2}"));
        sb.AppendLine(FormatLine("Total Gross Profit:", $"KSh {totalProfit:N2}"));
    }

    private void AppendCategorySalesSection(StringBuilder sb, List<CategorySalesReport> categories)
    {
        sb.AppendLine("SALES BY CATEGORY");
        sb.AppendLine(new string('-', LineWidth));

        foreach (var category in categories)
        {
            sb.AppendLine(FormatLine($"{category.CategoryName} ({category.ItemCount}):", $"KSh {category.NetSales:N2}"));
            sb.AppendLine($"  Qty: {category.QuantitySold:N0}  ({category.Percentage:N1}%)");
        }

        var total = categories.Sum(c => c.NetSales);
        sb.AppendLine();
        sb.AppendLine(FormatLine("Total:", $"KSh {total:N2}"));
    }

    private void AppendCashierSalesSection(StringBuilder sb, List<CashierSalesReport> cashiers)
    {
        sb.AppendLine("SALES BY CASHIER");
        sb.AppendLine(new string('-', LineWidth));

        foreach (var cashier in cashiers)
        {
            var name = cashier.CashierName.Length > 20
                ? cashier.CashierName[..17] + "..."
                : cashier.CashierName;
            sb.AppendLine($"{name}");
            sb.AppendLine($"  Trans: {cashier.TransactionCount}  Total: KSh {cashier.TotalSales:N2}");
            sb.AppendLine($"  Avg: KSh {cashier.AverageTransaction:N2}  Voids: {cashier.VoidCount}");
        }

        var total = cashiers.Sum(c => c.TotalSales);
        sb.AppendLine();
        sb.AppendLine(FormatLine("Total:", $"KSh {total:N2}"));
    }

    private void AppendPaymentMethodSection(StringBuilder sb, List<PaymentMethodSalesReport> methods)
    {
        sb.AppendLine("SALES BY PAYMENT METHOD");
        sb.AppendLine(new string('-', LineWidth));

        foreach (var method in methods)
        {
            sb.AppendLine(FormatLine($"{method.PaymentMethodName} ({method.TransactionCount}):", $"KSh {method.TotalAmount:N2}"));
            sb.AppendLine($"  ({method.Percentage:N1}% of total)");
        }

        var total = methods.Sum(m => m.TotalAmount);
        sb.AppendLine();
        sb.AppendLine(FormatLine("Total:", $"KSh {total:N2}"));
    }

    private void AppendHourlySalesSection(StringBuilder sb, List<HourlySalesReport> hourly)
    {
        sb.AppendLine("HOURLY SALES BREAKDOWN");
        sb.AppendLine(new string('-', LineWidth));

        foreach (var hour in hourly)
        {
            sb.AppendLine(FormatLine($"{hour.HourDisplay} ({hour.TransactionCount}):", $"KSh {hour.TotalSales:N2}"));
        }

        var total = hourly.Sum(h => h.TotalSales);
        var peakHour = hourly.OrderByDescending(h => h.TotalSales).FirstOrDefault();
        sb.AppendLine();
        sb.AppendLine(FormatLine("Total:", $"KSh {total:N2}"));
        if (peakHour != null)
        {
            sb.AppendLine($"Peak Hour: {peakHour.HourDisplay}");
        }
    }

    private static string CenterText(string text, int width)
    {
        if (text.Length >= width) return text[..width];
        var padding = (width - text.Length) / 2;
        return new string(' ', padding) + text;
    }

    private static string FormatLine(string label, string value)
    {
        var spaces = LineWidth - label.Length - value.Length;
        if (spaces < 1) spaces = 1;
        return label + new string(' ', spaces) + value;
    }

    /// <inheritdoc />
    public async Task PrintReportAsync(string content, string? title = null)
    {
        await Application.Current.Dispatcher.InvokeAsync(() =>
        {
            try
            {
                var document = new FlowDocument
                {
                    FontFamily = new FontFamily("Consolas"),
                    FontSize = 10,
                    PageWidth = 280,
                    PagePadding = new Thickness(10),
                    ColumnWidth = 280
                };

                var lines = content.Split('\n');
                foreach (var line in lines)
                {
                    var paragraph = new Paragraph(new Run(line))
                    {
                        Margin = new Thickness(0, 0, 0, 0),
                        LineHeight = 1
                    };
                    document.Blocks.Add(paragraph);
                }

                var printDialog = new PrintDialog();
                if (printDialog.ShowDialog() == true)
                {
                    var paginator = ((IDocumentPaginatorSource)document).DocumentPaginator;
                    printDialog.PrintDocument(paginator, title ?? "Report");
                    _logger.Information("Report printed successfully: {Title}", title);
                }
            }
            catch (Exception ex)
            {
                _logger.Error(ex, "Failed to print report: {Title}", title);
                throw;
            }
        });
    }

    /// <inheritdoc />
    public async Task ExportToPdfAsync(string content, string fileName)
    {
        await Task.Run(() =>
        {
            try
            {
                var documentsPath = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
                var filePath = Path.Combine(documentsPath, $"{fileName}_{DateTime.Now:yyyyMMdd_HHmmss}.html");

                // For now, save as HTML which can be opened and printed as PDF
                File.WriteAllText(filePath, content, Encoding.UTF8);
                _logger.Information("Report exported to HTML (PDF placeholder): {FilePath}", filePath);

                // Open the file for user to print as PDF
                System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo
                {
                    FileName = filePath,
                    UseShellExecute = true
                });
            }
            catch (Exception ex)
            {
                _logger.Error(ex, "Failed to export report to PDF: {FileName}", fileName);
                throw;
            }
        });
    }

    /// <inheritdoc />
    public async Task ExportToCsvAsync(string content, string fileName)
    {
        await Task.Run(() =>
        {
            try
            {
                var documentsPath = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
                var filePath = Path.Combine(documentsPath, $"{fileName}_{DateTime.Now:yyyyMMdd_HHmmss}.csv");

                File.WriteAllText(filePath, content, Encoding.UTF8);
                _logger.Information("Report exported to CSV: {FilePath}", filePath);

                // Open the file
                System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo
                {
                    FileName = filePath,
                    UseShellExecute = true
                });
            }
            catch (Exception ex)
            {
                _logger.Error(ex, "Failed to export report to CSV: {FileName}", fileName);
                throw;
            }
        });
    }
}
