using System.IO;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Media;
using HospitalityPOS.Core.DTOs;
using HospitalityPOS.Core.Enums;
using HospitalityPOS.Core.Interfaces;
using HospitalityPOS.Core.Models.Reports;
using Serilog;

namespace HospitalityPOS.WPF.Services;

/// <summary>
/// Service for printing sales reports to thermal or standard printers.
/// </summary>
public class ReportPrintService : IReportPrintService
{
    private readonly ILogger _logger;
    private const int LineWidth = 48; // 80mm thermal printer character width

    /// <summary>
    /// Initializes a new instance of the <see cref="ReportPrintService"/> class.
    /// </summary>
    /// <param name="logger">The logger.</param>
    public ReportPrintService(ILogger logger)
    {
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    /// <inheritdoc />
    public bool PrintSalesReport(SalesReportResult report)
    {
        if (report == null)
        {
            throw new ArgumentNullException(nameof(report));
        }

        try
        {
            var printContent = GeneratePrintContent(report);

            // Create a FlowDocument for printing
            var document = new FlowDocument
            {
                FontFamily = new FontFamily("Consolas"),
                FontSize = 10,
                PageWidth = 280, // ~80mm at 96 DPI
                PagePadding = new Thickness(10),
                ColumnWidth = 280
            };

            // Split content into lines and add paragraphs
            var lines = printContent.Split('\n');
            foreach (var line in lines)
            {
                var paragraph = new Paragraph(new Run(line))
                {
                    Margin = new Thickness(0, 0, 0, 0),
                    LineHeight = 1
                };
                document.Blocks.Add(paragraph);
            }

            // Show print dialog
            var printDialog = new PrintDialog();
            if (printDialog.ShowDialog() == true)
            {
                var paginator = ((IDocumentPaginatorSource)document).DocumentPaginator;
                printDialog.PrintDocument(paginator, "Sales Report");
                _logger.Information("Sales report printed successfully");
                return true;
            }

            _logger.Information("Print dialog cancelled by user");
            return false;
        }
        catch (Exception ex)
        {
            _logger.Error(ex, "Failed to print sales report");
            throw;
        }
    }

    /// <inheritdoc />
    public string GeneratePrintContent(SalesReportResult report)
    {
        var sb = new StringBuilder();

        // Header
        sb.AppendLine(new string('=', LineWidth));
        sb.AppendLine(CenterText("SALES REPORT", LineWidth));
        sb.AppendLine(new string('=', LineWidth));

        // Report Info
        sb.AppendLine($"From: {report.Parameters.StartDate:yyyy-MM-dd}");
        sb.AppendLine($"To:   {report.Parameters.EndDate:yyyy-MM-dd}");
        sb.AppendLine($"Generated: {report.GeneratedAt.ToLocalTime():yyyy-MM-dd HH:mm}");
        sb.AppendLine($"Generated by: {report.GeneratedBy}");
        sb.AppendLine(new string('-', LineWidth));

        // Sales Summary (always included)
        AppendSummarySection(sb, report.Summary);

        // Product Sales
        if (report.ProductSales.Count > 0)
        {
            sb.AppendLine(new string('-', LineWidth));
            AppendProductSalesSection(sb, report.ProductSales);
        }

        // Category Sales
        if (report.CategorySales.Count > 0)
        {
            sb.AppendLine(new string('-', LineWidth));
            AppendCategorySalesSection(sb, report.CategorySales);
        }

        // Cashier Sales
        if (report.CashierSales.Count > 0)
        {
            sb.AppendLine(new string('-', LineWidth));
            AppendCashierSalesSection(sb, report.CashierSales);
        }

        // Payment Method Sales
        if (report.PaymentMethodSales.Count > 0)
        {
            sb.AppendLine(new string('-', LineWidth));
            AppendPaymentMethodSection(sb, report.PaymentMethodSales);
        }

        // Hourly Sales
        if (report.HourlySales.Count > 0)
        {
            sb.AppendLine(new string('-', LineWidth));
            AppendHourlySalesSection(sb, report.HourlySales);
        }

        // Footer
        sb.AppendLine(new string('=', LineWidth));
        sb.AppendLine(CenterText("** END OF REPORT **", LineWidth));
        sb.AppendLine(new string('=', LineWidth));

        return sb.ToString();
    }

    private void AppendSummarySection(StringBuilder sb, DailySalesSummary summary)
    {
        sb.AppendLine("SALES SUMMARY");
        sb.AppendLine(new string('-', LineWidth));
        sb.AppendLine(FormatLine("Gross Sales:", $"KSh {summary.GrossSales:N2}"));
        sb.AppendLine(FormatLine("Discounts:", $"-KSh {summary.Discounts:N2}"));
        sb.AppendLine(FormatLine("Net Sales:", $"KSh {summary.NetSales:N2}"));
        sb.AppendLine(FormatLine("Tax Collected:", $"KSh {summary.TaxCollected:N2}"));
        sb.AppendLine(new string(' ', LineWidth - 20) + new string('-', 20));
        sb.AppendLine(FormatLine("TOTAL REVENUE:", $"KSh {summary.TotalRevenue:N2}"));
        sb.AppendLine();
        sb.AppendLine($"Transactions: {summary.TransactionCount}");
        sb.AppendLine($"Average Transaction: KSh {summary.AverageTransaction:N2}");
        if (summary.LargestTransaction > 0)
        {
            sb.AppendLine($"Largest Transaction: KSh {summary.LargestTransaction:N2}");
        }
        if (summary.VoidedCount > 0)
        {
            sb.AppendLine();
            sb.AppendLine($"Voided Transactions: {summary.VoidedCount}");
            sb.AppendLine($"Voided Amount: KSh {summary.VoidedAmount:N2}");
        }
    }

    private void AppendProductSalesSection(StringBuilder sb, List<ProductSalesReport> products)
    {
        sb.AppendLine("SALES BY PRODUCT");
        sb.AppendLine(new string('-', LineWidth));

        foreach (var product in products.Take(20)) // Limit to top 20 products
        {
            var name = product.ProductName.Length > 20
                ? product.ProductName[..17] + "..."
                : product.ProductName;
            sb.AppendLine($"{name}");
            sb.AppendLine($"  Qty: {product.QuantitySold:N0}  Net: KSh {product.NetSales:N2} ({product.Percentage:N1}%)");
        }

        if (products.Count > 20)
        {
            sb.AppendLine($"... and {products.Count - 20} more products");
        }

        var totalNet = products.Sum(p => p.NetSales);
        var totalProfit = products.Sum(p => p.GrossProfit);
        sb.AppendLine();
        sb.AppendLine(FormatLine("Total Net Sales:", $"KSh {totalNet:N2}"));
        sb.AppendLine(FormatLine("Total Gross Profit:", $"KSh {totalProfit:N2}"));
    }

    private void AppendCategorySalesSection(StringBuilder sb, List<CategorySalesReport> categories)
    {
        sb.AppendLine("SALES BY CATEGORY");
        sb.AppendLine(new string('-', LineWidth));

        foreach (var category in categories)
        {
            sb.AppendLine(FormatLine($"{category.CategoryName} ({category.ItemCount}):", $"KSh {category.NetSales:N2}"));
            sb.AppendLine($"  Qty: {category.QuantitySold:N0}  ({category.Percentage:N1}%)");
        }

        var total = categories.Sum(c => c.NetSales);
        sb.AppendLine();
        sb.AppendLine(FormatLine("Total:", $"KSh {total:N2}"));
    }

    private void AppendCashierSalesSection(StringBuilder sb, List<CashierSalesReport> cashiers)
    {
        sb.AppendLine("SALES BY CASHIER");
        sb.AppendLine(new string('-', LineWidth));

        foreach (var cashier in cashiers)
        {
            var name = cashier.CashierName.Length > 20
                ? cashier.CashierName[..17] + "..."
                : cashier.CashierName;
            sb.AppendLine($"{name}");
            sb.AppendLine($"  Trans: {cashier.TransactionCount}  Total: KSh {cashier.TotalSales:N2}");
            sb.AppendLine($"  Avg: KSh {cashier.AverageTransaction:N2}  Voids: {cashier.VoidCount}");
        }

        var total = cashiers.Sum(c => c.TotalSales);
        sb.AppendLine();
        sb.AppendLine(FormatLine("Total:", $"KSh {total:N2}"));
    }

    private void AppendPaymentMethodSection(StringBuilder sb, List<PaymentMethodSalesReport> methods)
    {
        sb.AppendLine("SALES BY PAYMENT METHOD");
        sb.AppendLine(new string('-', LineWidth));

        foreach (var method in methods)
        {
            sb.AppendLine(FormatLine($"{method.PaymentMethodName} ({method.TransactionCount}):", $"KSh {method.TotalAmount:N2}"));
            sb.AppendLine($"  ({method.Percentage:N1}% of total)");
        }

        var total = methods.Sum(m => m.TotalAmount);
        sb.AppendLine();
        sb.AppendLine(FormatLine("Total:", $"KSh {total:N2}"));
    }

    private void AppendHourlySalesSection(StringBuilder sb, List<HourlySalesReport> hourly)
    {
        sb.AppendLine("HOURLY SALES BREAKDOWN");
        sb.AppendLine(new string('-', LineWidth));

        foreach (var hour in hourly)
        {
            sb.AppendLine(FormatLine($"{hour.HourDisplay} ({hour.TransactionCount}):", $"KSh {hour.TotalSales:N2}"));
        }

        var total = hourly.Sum(h => h.TotalSales);
        var peakHour = hourly.OrderByDescending(h => h.TotalSales).FirstOrDefault();
        sb.AppendLine();
        sb.AppendLine(FormatLine("Total:", $"KSh {total:N2}"));
        if (peakHour != null)
        {
            sb.AppendLine($"Peak Hour: {peakHour.HourDisplay}");
        }
    }

    private static string CenterText(string text, int width)
    {
        if (text.Length >= width) return text[..width];
        var padding = (width - text.Length) / 2;
        return new string(' ', padding) + text;
    }

    private static string FormatLine(string label, string value)
    {
        var spaces = LineWidth - label.Length - value.Length;
        if (spaces < 1) spaces = 1;
        return label + new string(' ', spaces) + value;
    }

    /// <inheritdoc />
    public async Task PrintReportAsync(string content, string? title = null)
    {
        await Application.Current.Dispatcher.InvokeAsync(() =>
        {
            try
            {
                var document = new FlowDocument
                {
                    FontFamily = new FontFamily("Consolas"),
                    FontSize = 10,
                    PageWidth = 280,
                    PagePadding = new Thickness(10),
                    ColumnWidth = 280
                };

                var lines = content.Split('\n');
                foreach (var line in lines)
                {
                    var paragraph = new Paragraph(new Run(line))
                    {
                        Margin = new Thickness(0, 0, 0, 0),
                        LineHeight = 1
                    };
                    document.Blocks.Add(paragraph);
                }

                var printDialog = new PrintDialog();
                if (printDialog.ShowDialog() == true)
                {
                    var paginator = ((IDocumentPaginatorSource)document).DocumentPaginator;
                    printDialog.PrintDocument(paginator, title ?? "Report");
                    _logger.Information("Report printed successfully: {Title}", title);
                }
            }
            catch (Exception ex)
            {
                _logger.Error(ex, "Failed to print report: {Title}", title);
                throw;
            }
        });
    }

    /// <inheritdoc />
    public async Task ExportToPdfAsync(string content, string fileName)
    {
        await Task.Run(() =>
        {
            try
            {
                var documentsPath = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
                var filePath = Path.Combine(documentsPath, $"{fileName}_{DateTime.Now:yyyyMMdd_HHmmss}.html");

                // For now, save as HTML which can be opened and printed as PDF
                File.WriteAllText(filePath, content, Encoding.UTF8);
                _logger.Information("Report exported to HTML (PDF placeholder): {FilePath}", filePath);

                // Open the file for user to print as PDF
                System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo
                {
                    FileName = filePath,
                    UseShellExecute = true
                });
            }
            catch (Exception ex)
            {
                _logger.Error(ex, "Failed to export report to PDF: {FileName}", fileName);
                throw;
            }
        });
    }

    /// <inheritdoc />
    public async Task ExportToCsvAsync(string content, string fileName)
    {
        await Task.Run(() =>
        {
            try
            {
                var documentsPath = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
                var filePath = Path.Combine(documentsPath, $"{fileName}_{DateTime.Now:yyyyMMdd_HHmmss}.csv");

                File.WriteAllText(filePath, content, Encoding.UTF8);
                _logger.Information("Report exported to CSV: {FilePath}", filePath);

                // Open the file
                System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo
                {
                    FileName = filePath,
                    UseShellExecute = true
                });
            }
            catch (Exception ex)
            {
                _logger.Error(ex, "Failed to export report to CSV: {FileName}", fileName);
                throw;
            }
        });
    }

    #region X-Report and Z-Report Thermal Printing

    /// <inheritdoc />
    public async Task PrintXReportAsync(XReportData report)
    {
        var content = GenerateXReportThermalContent(report);
        await PrintReportAsync(content, $"X-Report {report.ReportNumber}");
    }

    /// <inheritdoc />
    public async Task PrintZReportAsync(ZReport report)
    {
        var content = GenerateZReportThermalContent(report);
        await PrintReportAsync(content, $"Z-Report {report.ReportNumberFormatted}");
    }

    /// <inheritdoc />
    public async Task PrintCombinedXReportAsync(CombinedXReportData report)
    {
        var content = GenerateCombinedXReportThermalContent(report);
        await PrintReportAsync(content, $"Combined X-Report {report.ReportNumber}");
    }

    /// <inheritdoc />
    public async Task PrintCombinedZReportAsync(CombinedZReportPreview report)
    {
        var content = GenerateCombinedZReportThermalContent(report);
        await PrintReportAsync(content, "Combined Z-Report Preview");
    }

    /// <inheritdoc />
    public string GenerateXReportThermalContent(XReportData report)
    {
        var sb = new StringBuilder();

        // Header
        sb.AppendLine(new string('=', LineWidth));
        sb.AppendLine(CenterText(report.BusinessName, LineWidth));
        sb.AppendLine(CenterText("X-REPORT", LineWidth));
        sb.AppendLine(new string('=', LineWidth));

        // Terminal Info
        if (!string.IsNullOrEmpty(report.TerminalCode))
        {
            sb.AppendLine($"Terminal: {report.TerminalCode}");
            sb.AppendLine($"          {report.TerminalName}");
        }
        sb.AppendLine($"Report #: {report.ReportNumber}");
        sb.AppendLine($"Generated: {report.GeneratedAt.ToLocalTime():yyyy-MM-dd HH:mm}");
        sb.AppendLine($"By: {report.GeneratedByName}");
        sb.AppendLine(new string('-', LineWidth));

        // Shift Info
        sb.AppendLine("SHIFT INFORMATION");
        sb.AppendLine(new string('-', LineWidth));
        sb.AppendLine(FormatLine("Started:", report.ShiftStarted.ToLocalTime().ToString("yyyy-MM-dd HH:mm")));
        sb.AppendLine(FormatLine("Duration:", report.ShiftDurationFormatted));
        sb.AppendLine(new string('-', LineWidth));

        // Sales Summary
        sb.AppendLine("SALES SUMMARY");
        sb.AppendLine(new string('-', LineWidth));
        sb.AppendLine(FormatLine("Gross Sales:", $"KSh {report.GrossSales:N2}"));
        sb.AppendLine(FormatLine("Discounts:", $"-KSh {report.Discounts:N2}"));
        sb.AppendLine(FormatLine("Refunds:", $"-KSh {report.Refunds:N2}"));
        sb.AppendLine(FormatLine("Net Sales:", $"KSh {report.NetSales:N2}"));
        sb.AppendLine(FormatLine("Tax:", $"KSh {report.TaxAmount:N2}"));
        sb.AppendLine(FormatLine("Tips:", $"KSh {report.TipsCollected:N2}"));
        sb.AppendLine(new string(' ', LineWidth - 20) + new string('-', 20));
        sb.AppendLine(FormatLine("GRAND TOTAL:", $"KSh {report.GrandTotal:N2}"));
        sb.AppendLine(new string('-', LineWidth));

        // Payment Breakdown by Type
        sb.AppendLine("PAYMENT BREAKDOWN");
        sb.AppendLine(new string('-', LineWidth));
        if (report.PaymentTypeBreakdown?.Count > 0)
        {
            foreach (var pt in report.PaymentTypeBreakdown)
            {
                sb.AppendLine(FormatLine($"[{pt.PaymentTypeName}] ({pt.TotalTransactionCount}):", $"KSh {pt.TotalAmount:N2}"));
                foreach (var pm in pt.Methods)
                {
                    sb.AppendLine(FormatLine($"  {pm.PaymentMethodName} ({pm.TransactionCount}):", $"KSh {pm.Amount:N2}"));
                }
            }
        }
        else if (report.PaymentBreakdown?.Count > 0)
        {
            foreach (var pm in report.PaymentBreakdown)
            {
                sb.AppendLine(FormatLine($"{pm.PaymentMethodName} ({pm.TransactionCount}):", $"KSh {pm.Amount:N2}"));
            }
        }
        sb.AppendLine(new string('-', LineWidth));

        // Statistics
        sb.AppendLine("STATISTICS");
        sb.AppendLine(new string('-', LineWidth));
        sb.AppendLine(FormatLine("Transactions:", report.TransactionCount.ToString()));
        sb.AppendLine(FormatLine("Average Transaction:", $"KSh {report.AverageTransaction:N2}"));
        sb.AppendLine(FormatLine("Voids:", report.VoidCount.ToString()));
        sb.AppendLine(FormatLine("Refunds:", report.RefundCount.ToString()));
        sb.AppendLine(new string('-', LineWidth));

        // Cash Drawer
        sb.AppendLine("CASH DRAWER");
        sb.AppendLine(new string('-', LineWidth));
        sb.AppendLine(FormatLine("Opening Float:", $"KSh {report.OpeningFloat:N2}"));
        sb.AppendLine(FormatLine("+ Cash Received:", $"KSh {report.CashReceived:N2}"));
        sb.AppendLine(FormatLine("- Cash Refunds:", $"KSh {report.CashRefunds:N2}"));
        sb.AppendLine(FormatLine("- Cash Payouts:", $"KSh {report.CashPayouts:N2}"));
        sb.AppendLine(new string(' ', LineWidth - 20) + new string('-', 20));
        sb.AppendLine(FormatLine("EXPECTED CASH:", $"KSh {report.ExpectedCash:N2}"));
        sb.AppendLine(new string('=', LineWidth));

        // Footer
        sb.AppendLine(CenterText("** INTERIM REPORT **", LineWidth));
        sb.AppendLine(CenterText("Work Period Still Open", LineWidth));
        sb.AppendLine(new string('=', LineWidth));

        return sb.ToString();
    }

    /// <inheritdoc />
    public string GenerateZReportThermalContent(ZReport report)
    {
        var sb = new StringBuilder();

        // Header
        sb.AppendLine(new string('=', LineWidth));
        sb.AppendLine(CenterText(report.BusinessName, LineWidth));
        sb.AppendLine(CenterText("*** Z-REPORT ***", LineWidth));
        sb.AppendLine(new string('=', LineWidth));

        // Terminal Info
        if (!string.IsNullOrEmpty(report.TerminalCode))
        {
            sb.AppendLine($"Terminal: {report.TerminalCode}");
            sb.AppendLine($"          {report.TerminalName}");
        }
        sb.AppendLine($"Z-Report #: {report.ReportNumberFormatted}");
        sb.AppendLine(new string('-', LineWidth));

        // Work Period Info
        sb.AppendLine("WORK PERIOD");
        sb.AppendLine(new string('-', LineWidth));
        sb.AppendLine(FormatLine("Opened:", report.WorkPeriodOpenedAt.ToLocalTime().ToString("yyyy-MM-dd HH:mm")));
        sb.AppendLine(FormatLine("Closed:", report.WorkPeriodClosedAt.ToLocalTime().ToString("yyyy-MM-dd HH:mm")));
        sb.AppendLine(FormatLine("Duration:", $"{(int)report.Duration.TotalHours}h {report.Duration.Minutes}m"));
        sb.AppendLine(new string('-', LineWidth));

        // Sales Summary
        sb.AppendLine("FINAL SALES SUMMARY");
        sb.AppendLine(new string('-', LineWidth));
        sb.AppendLine(FormatLine("Gross Sales:", $"KSh {report.GrossSales:N2}"));
        sb.AppendLine(FormatLine("Discounts:", $"-KSh {report.TotalDiscounts:N2}"));
        sb.AppendLine(FormatLine("Net Sales:", $"KSh {report.NetSales:N2}"));
        sb.AppendLine(FormatLine("Tax Collected:", $"KSh {report.TaxCollected:N2}"));
        sb.AppendLine(new string(' ', LineWidth - 20) + new string('-', 20));
        sb.AppendLine(FormatLine("GRAND TOTAL:", $"KSh {report.GrandTotal:N2}"));
        sb.AppendLine(new string('-', LineWidth));

        // Payment Methods
        sb.AppendLine("PAYMENT METHODS");
        sb.AppendLine(new string('-', LineWidth));
        foreach (var pm in report.SalesByPaymentMethod)
        {
            sb.AppendLine(FormatLine($"{pm.PaymentMethod} ({pm.TransactionCount}):", $"KSh {pm.TotalAmount:N2}"));
        }
        sb.AppendLine(new string('-', LineWidth));

        // Cash Drawer Reconciliation
        sb.AppendLine("CASH DRAWER RECONCILIATION");
        sb.AppendLine(new string('-', LineWidth));
        sb.AppendLine(FormatLine("Opening Float:", $"KSh {report.OpeningFloat:N2}"));
        sb.AppendLine(FormatLine("+ Cash Sales:", $"KSh {report.CashSales:N2}"));
        sb.AppendLine(FormatLine("- Cash Payouts:", $"KSh {report.CashPayouts:N2}"));
        sb.AppendLine(new string(' ', LineWidth - 20) + new string('-', 20));
        sb.AppendLine(FormatLine("EXPECTED CASH:", $"KSh {report.ExpectedCash:N2}"));
        sb.AppendLine(FormatLine("ACTUAL CASH:", $"KSh {report.ActualCash:N2}"));
        sb.AppendLine(new string(' ', LineWidth - 20) + new string('-', 20));
        sb.AppendLine(FormatLine("VARIANCE:", $"KSh {report.Variance:N2}"));
        sb.AppendLine(FormatLine("Status:", report.VarianceStatus));
        sb.AppendLine(new string('-', LineWidth));

        // Receipts Summary
        sb.AppendLine("RECEIPTS SUMMARY");
        sb.AppendLine(new string('-', LineWidth));
        sb.AppendLine(FormatLine($"Settled ({report.SettledReceiptsCount}):", $"KSh {report.SettledReceiptsTotal:N2}"));
        sb.AppendLine(FormatLine($"Pending ({report.PendingReceiptsCount}):", $"KSh {report.PendingReceiptsTotal:N2}"));
        sb.AppendLine(FormatLine($"Voided ({report.VoidCount}):", $"KSh {report.VoidTotal:N2}"));
        sb.AppendLine(new string('=', LineWidth));

        // Footer
        sb.AppendLine(CenterText("*** END OF Z-REPORT ***", LineWidth));
        sb.AppendLine(CenterText("OFFICIAL DOCUMENT", LineWidth));
        sb.AppendLine($"Printed: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine(new string('=', LineWidth));

        return sb.ToString();
    }

    private string GenerateCombinedXReportThermalContent(CombinedXReportData report)
    {
        var sb = new StringBuilder();

        // Header
        sb.AppendLine(new string('=', LineWidth));
        sb.AppendLine(CenterText(report.BusinessName, LineWidth));
        sb.AppendLine(CenterText("COMBINED X-REPORT", LineWidth));
        sb.AppendLine(CenterText($"({report.TerminalCount} Terminals)", LineWidth));
        sb.AppendLine(new string('=', LineWidth));

        sb.AppendLine($"Report #: {report.ReportNumber}");
        sb.AppendLine($"Generated: {report.GeneratedAt.ToLocalTime():yyyy-MM-dd HH:mm}");
        sb.AppendLine($"By: {report.GeneratedByName}");
        sb.AppendLine(new string('-', LineWidth));

        // Combined Sales
        sb.AppendLine("COMBINED SALES SUMMARY");
        sb.AppendLine(new string('-', LineWidth));
        sb.AppendLine(FormatLine("Gross Sales:", $"KSh {report.GrossSales:N2}"));
        sb.AppendLine(FormatLine("Discounts:", $"-KSh {report.Discounts:N2}"));
        sb.AppendLine(FormatLine("Refunds:", $"-KSh {report.Refunds:N2}"));
        sb.AppendLine(FormatLine("Net Sales:", $"KSh {report.NetSales:N2}"));
        sb.AppendLine(FormatLine("Tax:", $"KSh {report.TaxAmount:N2}"));
        sb.AppendLine(new string(' ', LineWidth - 20) + new string('-', 20));
        sb.AppendLine(FormatLine("GRAND TOTAL:", $"KSh {report.GrandTotal:N2}"));
        sb.AppendLine(new string('-', LineWidth));

        // Terminal Breakdown
        sb.AppendLine("TERMINAL BREAKDOWN");
        sb.AppendLine(new string('-', LineWidth));
        foreach (var t in report.TerminalBreakdown)
        {
            var status = t.IsOnline ? "" : " [OFFLINE]";
            sb.AppendLine($"{t.TerminalCode}{status}");
            sb.AppendLine(FormatLine($"  Net Sales:", $"KSh {t.NetSales:N2}"));
            sb.AppendLine(FormatLine($"  Transactions:", t.TransactionCount.ToString()));
        }
        sb.AppendLine(new string('-', LineWidth));

        // Combined Payment Breakdown
        sb.AppendLine("PAYMENT BREAKDOWN");
        sb.AppendLine(new string('-', LineWidth));
        foreach (var pm in report.PaymentBreakdown)
        {
            sb.AppendLine(FormatLine($"{pm.PaymentMethodName} ({pm.TransactionCount}):", $"KSh {pm.Amount:N2}"));
        }
        sb.AppendLine(new string('-', LineWidth));

        // Combined Cash Drawer
        sb.AppendLine("COMBINED CASH DRAWER");
        sb.AppendLine(new string('-', LineWidth));
        sb.AppendLine(FormatLine("Total Expected:", $"KSh {report.ExpectedCash:N2}"));
        sb.AppendLine(new string('=', LineWidth));

        // Footer
        sb.AppendLine(CenterText("** COMBINED INTERIM REPORT **", LineWidth));
        sb.AppendLine(new string('=', LineWidth));

        return sb.ToString();
    }

    private string GenerateCombinedZReportThermalContent(CombinedZReportPreview report)
    {
        var sb = new StringBuilder();

        // Header
        sb.AppendLine(new string('=', LineWidth));
        sb.AppendLine(CenterText("COMBINED Z-REPORT PREVIEW", LineWidth));
        sb.AppendLine(CenterText($"({report.TerminalCount} Terminals)", LineWidth));
        sb.AppendLine(new string('=', LineWidth));

        sb.AppendLine($"Work Period: {report.WorkPeriodStart.ToLocalTime():yyyy-MM-dd HH:mm}");
        sb.AppendLine(new string('-', LineWidth));

        // Status
        sb.AppendLine("STATUS OVERVIEW");
        sb.AppendLine(new string('-', LineWidth));
        sb.AppendLine(FormatLine("Total Terminals:", report.TerminalCount.ToString()));
        sb.AppendLine(FormatLine("Z-Reports Completed:", report.CompletedZReportCount.ToString()));
        sb.AppendLine(FormatLine("Pending:", report.PendingZReportCount.ToString()));
        sb.AppendLine(new string('-', LineWidth));

        // Combined Totals
        sb.AppendLine("COMBINED TOTALS");
        sb.AppendLine(new string('-', LineWidth));
        sb.AppendLine(FormatLine("Total Gross Sales:", $"KSh {report.TotalGrossSales:N2}"));
        sb.AppendLine(FormatLine("Total Net Sales:", $"KSh {report.TotalNetSales:N2}"));
        sb.AppendLine(FormatLine("Total Grand Total:", $"KSh {report.TotalGrandTotal:N2}"));
        sb.AppendLine(FormatLine("Total Transactions:", report.TotalTransactionCount.ToString()));
        sb.AppendLine(new string('-', LineWidth));

        // Terminal Status
        sb.AppendLine("TERMINAL STATUS");
        sb.AppendLine(new string('-', LineWidth));
        foreach (var t in report.TerminalBreakdown)
        {
            var status = t.HasZReport ? "[DONE]" : "[PENDING]";
            sb.AppendLine($"{status} {t.TerminalCode}");
            sb.AppendLine(FormatLine($"  Net Sales:", $"KSh {t.NetSales:N2}"));
        }
        sb.AppendLine(new string('=', LineWidth));

        // Footer
        sb.AppendLine(CenterText("** PREVIEW ONLY **", LineWidth));
        sb.AppendLine($"Printed: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine(new string('=', LineWidth));

        return sb.ToString();
    }

    #endregion

    #region Inventory Report Printing

    /// <inheritdoc />
    public async Task PrintCurrentStockReportAsync(CurrentStockReportResult report)
    {
        var content = GenerateCurrentStockContent(report);
        await PrintReportAsync(content, "Current Stock Report");
    }

    /// <inheritdoc />
    public async Task PrintLowStockReportAsync(LowStockReportResult report)
    {
        var content = GenerateLowStockContent(report);
        await PrintReportAsync(content, "Low Stock Alert Report");
    }

    /// <inheritdoc />
    public async Task PrintStockMovementReportAsync(StockMovementReportResult report)
    {
        var content = GenerateStockMovementContent(report);
        await PrintReportAsync(content, "Stock Movement Report");
    }

    /// <inheritdoc />
    public async Task PrintStockValuationReportAsync(StockValuationReportResult report)
    {
        var content = GenerateStockValuationContent(report);
        await PrintReportAsync(content, "Stock Valuation Report");
    }

    /// <inheritdoc />
    public async Task PrintDeadStockReportAsync(DeadStockReportResult report)
    {
        var content = GenerateDeadStockContent(report);
        await PrintReportAsync(content, "Dead Stock Report");
    }

    private string GenerateCurrentStockContent(CurrentStockReportResult report)
    {
        var sb = new StringBuilder();

        // Header
        sb.AppendLine(new string('=', LineWidth));
        sb.AppendLine(CenterText("CURRENT STOCK REPORT", LineWidth));
        sb.AppendLine(new string('=', LineWidth));

        // Report Info
        sb.AppendLine($"Generated: {report.GeneratedAt.ToLocalTime():yyyy-MM-dd HH:mm}");
        sb.AppendLine($"Generated by: {report.GeneratedBy}");
        sb.AppendLine(new string('-', LineWidth));

        // Summary
        sb.AppendLine("SUMMARY");
        sb.AppendLine(new string('-', LineWidth));
        sb.AppendLine(FormatLine("Total SKUs:", $"{report.TotalSkuCount}"));
        sb.AppendLine(FormatLine("Items in Stock:", $"{report.ItemsInStock}"));
        sb.AppendLine(FormatLine("Out of Stock:", $"{report.OutOfStockCount}"));
        sb.AppendLine(FormatLine("Low Stock:", $"{report.LowStockCount}"));
        sb.AppendLine(new string('-', LineWidth));
        sb.AppendLine(FormatLine("Total Stock Value:", $"KSh {report.TotalStockValue:N2}"));
        sb.AppendLine(FormatLine("Total Retail Value:", $"KSh {report.TotalRetailValue:N2}"));
        sb.AppendLine(FormatLine("Potential Profit:", $"KSh {report.PotentialProfit:N2}"));
        sb.AppendLine(new string('-', LineWidth));

        // Items
        sb.AppendLine("STOCK ITEMS");
        sb.AppendLine(new string('-', LineWidth));

        foreach (var item in report.Items.Take(50))
        {
            var name = item.ProductName.Length > 24
                ? item.ProductName[..21] + "..."
                : item.ProductName;
            var statusTag = item.Status switch
            {
                "OUT" => "[OUT]",
                "LOW" => "[LOW]",
                _ => ""
            };
            sb.AppendLine($"{name} {statusTag}");
            sb.AppendLine($"  {item.ProductCode}  Qty: {item.CurrentStock:N0} {item.StockUnit}");
            sb.AppendLine($"  Value: KSh {item.StockValue:N2}");
        }

        if (report.Items.Count > 50)
        {
            sb.AppendLine($"... and {report.Items.Count - 50} more items");
        }

        // Footer
        sb.AppendLine(new string('=', LineWidth));
        sb.AppendLine(CenterText("** END OF REPORT **", LineWidth));
        sb.AppendLine(new string('=', LineWidth));

        return sb.ToString();
    }

    private string GenerateLowStockContent(LowStockReportResult report)
    {
        var sb = new StringBuilder();

        // Header
        sb.AppendLine(new string('=', LineWidth));
        sb.AppendLine(CenterText("LOW STOCK ALERT REPORT", LineWidth));
        sb.AppendLine(new string('=', LineWidth));

        // Report Info
        sb.AppendLine($"Generated: {report.GeneratedAt.ToLocalTime():yyyy-MM-dd HH:mm}");
        sb.AppendLine($"Generated by: {report.GeneratedBy}");
        sb.AppendLine(new string('-', LineWidth));

        // Alert Summary
        sb.AppendLine("ALERT SUMMARY");
        sb.AppendLine(new string('-', LineWidth));
        sb.AppendLine(FormatLine("CRITICAL (Out of Stock):", $"{report.CriticalCount} items"));
        sb.AppendLine(FormatLine("LOW (Below Minimum):", $"{report.LowStockCount} items"));
        sb.AppendLine(FormatLine("Total Reorder Value:", $"KSh {report.TotalReorderValue:N2}"));
        sb.AppendLine(new string('-', LineWidth));

        // Critical Items First
        var criticalItems = report.Items.Where(i => i.IsCritical).ToList();
        if (criticalItems.Count > 0)
        {
            sb.AppendLine("*** CRITICAL - OUT OF STOCK ***");
            sb.AppendLine(new string('-', LineWidth));

            foreach (var item in criticalItems.Take(25))
            {
                var name = item.ProductName.Length > 24
                    ? item.ProductName[..21] + "..."
                    : item.ProductName;
                sb.AppendLine($"[CRITICAL] {name}");
                sb.AppendLine($"  Current: {item.CurrentStock:N0}  Min: {item.MinStock:N0}");
                sb.AppendLine($"  Reorder: {item.ReorderQty:N0}  Value: KSh {item.ReorderValue:N2}");
            }
            sb.AppendLine(new string('-', LineWidth));
        }

        // Low Stock Items
        var lowItems = report.Items.Where(i => !i.IsCritical).ToList();
        if (lowItems.Count > 0)
        {
            sb.AppendLine("LOW STOCK ITEMS");
            sb.AppendLine(new string('-', LineWidth));

            foreach (var item in lowItems.Take(25))
            {
                var name = item.ProductName.Length > 24
                    ? item.ProductName[..21] + "..."
                    : item.ProductName;
                sb.AppendLine($"[LOW] {name}");
                sb.AppendLine($"  Current: {item.CurrentStock:N0}  Min: {item.MinStock:N0}");
                sb.AppendLine($"  Reorder: {item.ReorderQty:N0}  Value: KSh {item.ReorderValue:N2}");
            }
        }

        if (report.Items.Count > 50)
        {
            sb.AppendLine($"... and {report.Items.Count - 50} more items");
        }

        // Footer
        sb.AppendLine(new string('=', LineWidth));
        sb.AppendLine(CenterText("** END OF REPORT **", LineWidth));
        sb.AppendLine(new string('=', LineWidth));

        return sb.ToString();
    }

    private string GenerateStockMovementContent(StockMovementReportResult report)
    {
        var sb = new StringBuilder();

        // Header
        sb.AppendLine(new string('=', LineWidth));
        sb.AppendLine(CenterText("STOCK MOVEMENT REPORT", LineWidth));
        sb.AppendLine(new string('=', LineWidth));

        // Report Info
        sb.AppendLine($"Period: {report.Parameters.StartDate:yyyy-MM-dd} to {report.Parameters.EndDate:yyyy-MM-dd}");
        sb.AppendLine($"Generated: {report.GeneratedAt.ToLocalTime():yyyy-MM-dd HH:mm}");
        sb.AppendLine($"Generated by: {report.GeneratedBy}");
        sb.AppendLine(new string('-', LineWidth));

        // Movement Summary
        sb.AppendLine("MOVEMENT SUMMARY");
        sb.AppendLine(new string('-', LineWidth));
        sb.AppendLine(FormatLine("Total Received:", $"+{report.TotalReceived:N0}"));
        sb.AppendLine(FormatLine("Total Sold:", $"-{report.TotalSold:N0}"));
        sb.AppendLine(FormatLine("Adjustments:", $"{report.TotalAdjusted:N0}"));
        sb.AppendLine(new string(' ', LineWidth - 20) + new string('-', 20));
        sb.AppendLine(FormatLine("Net Movement:", $"{report.NetMovement:N0}"));
        sb.AppendLine(new string('-', LineWidth));

        // Movement Details
        sb.AppendLine($"MOVEMENTS ({report.Items.Count} of {report.TotalCount})");
        sb.AppendLine(new string('-', LineWidth));

        foreach (var item in report.Items.Take(40))
        {
            var name = item.ProductName.Length > 20
                ? item.ProductName[..17] + "..."
                : item.ProductName;
            var qtyStr = item.Quantity >= 0 ? $"+{item.Quantity:N0}" : $"{item.Quantity:N0}";
            sb.AppendLine($"{item.Date.ToLocalTime():MM-dd HH:mm} {item.MovementType}");
            sb.AppendLine($"  {name}");
            sb.AppendLine($"  Qty: {qtyStr}  Ref: {item.Reference}");
        }

        if (report.TotalCount > 40)
        {
            sb.AppendLine($"... and {report.TotalCount - 40} more movements");
        }

        // Footer
        sb.AppendLine(new string('=', LineWidth));
        sb.AppendLine(CenterText("** END OF REPORT **", LineWidth));
        sb.AppendLine(new string('=', LineWidth));

        return sb.ToString();
    }

    private string GenerateStockValuationContent(StockValuationReportResult report)
    {
        var sb = new StringBuilder();

        // Header
        sb.AppendLine(new string('=', LineWidth));
        sb.AppendLine(CenterText("STOCK VALUATION REPORT", LineWidth));
        sb.AppendLine(new string('=', LineWidth));

        // Report Info
        sb.AppendLine($"As of: {report.AsOfDate.ToLocalTime():yyyy-MM-dd HH:mm}");
        sb.AppendLine($"Generated: {report.GeneratedAt.ToLocalTime():yyyy-MM-dd HH:mm}");
        sb.AppendLine($"Generated by: {report.GeneratedBy}");
        sb.AppendLine(new string('-', LineWidth));

        // Overall Summary
        sb.AppendLine("VALUATION SUMMARY");
        sb.AppendLine(new string('-', LineWidth));
        sb.AppendLine(FormatLine("Total Cost Value:", $"KSh {report.TotalCostValue:N2}"));
        sb.AppendLine(FormatLine("Total Retail Value:", $"KSh {report.TotalRetailValue:N2}"));
        sb.AppendLine(FormatLine("Potential Profit:", $"KSh {report.PotentialProfit:N2}"));
        sb.AppendLine(FormatLine("Overall Margin:", $"{report.MarginPercentage:N1}%"));
        sb.AppendLine(new string('-', LineWidth));

        // Category Breakdown
        sb.AppendLine("BREAKDOWN BY CATEGORY");
        sb.AppendLine(new string('-', LineWidth));

        foreach (var cat in report.Categories.OrderByDescending(c => c.CostValue))
        {
            var name = cat.CategoryName.Length > 20
                ? cat.CategoryName[..17] + "..."
                : cat.CategoryName;
            sb.AppendLine($"{name} ({cat.ItemCount} items)");
            sb.AppendLine($"  Units: {cat.TotalUnits:N0}");
            sb.AppendLine($"  Cost: KSh {cat.CostValue:N2}");
            sb.AppendLine($"  Retail: KSh {cat.RetailValue:N2}");
            sb.AppendLine($"  Margin: {cat.MarginPercentage:N1}%");
        }

        // Footer
        sb.AppendLine(new string('=', LineWidth));
        sb.AppendLine(CenterText("** END OF REPORT **", LineWidth));
        sb.AppendLine(new string('=', LineWidth));

        return sb.ToString();
    }

    private string GenerateDeadStockContent(DeadStockReportResult report)
    {
        var sb = new StringBuilder();

        // Header
        sb.AppendLine(new string('=', LineWidth));
        sb.AppendLine(CenterText("DEAD STOCK REPORT", LineWidth));
        sb.AppendLine(new string('=', LineWidth));

        // Report Info
        sb.AppendLine($"Threshold: No movement for {report.DaysThreshold} days");
        sb.AppendLine($"Generated: {report.GeneratedAt.ToLocalTime():yyyy-MM-dd HH:mm}");
        sb.AppendLine($"Generated by: {report.GeneratedBy}");
        sb.AppendLine(new string('-', LineWidth));

        // Summary
        sb.AppendLine("DEAD STOCK SUMMARY");
        sb.AppendLine(new string('-', LineWidth));
        sb.AppendLine(FormatLine("Total Dead Stock Items:", $"{report.TotalCount}"));
        sb.AppendLine(FormatLine("Total Dead Stock Value:", $"KSh {report.TotalValue:N2}"));
        sb.AppendLine(new string('-', LineWidth));

        // Items
        sb.AppendLine("DEAD STOCK ITEMS");
        sb.AppendLine(new string('-', LineWidth));

        foreach (var item in report.Items.Take(50))
        {
            var name = item.ProductName.Length > 24
                ? item.ProductName[..21] + "..."
                : item.ProductName;
            var lastMove = item.LastMovementDate.HasValue
                ? item.LastMovementDate.Value.ToLocalTime().ToString("yyyy-MM-dd")
                : "Never";
            sb.AppendLine($"{name}");
            sb.AppendLine($"  {item.ProductCode}  Qty: {item.CurrentStock:N0}");
            sb.AppendLine($"  Value: KSh {item.StockValue:N2}");
            sb.AppendLine($"  Last Movement: {lastMove} ({item.DaysSinceMovement} days)");
        }

        if (report.Items.Count > 50)
        {
            sb.AppendLine($"... and {report.Items.Count - 50} more items");
        }

        // Footer
        sb.AppendLine(new string('=', LineWidth));
        sb.AppendLine(CenterText("** END OF REPORT **", LineWidth));
        sb.AppendLine(new string('=', LineWidth));

        return sb.ToString();
    }

    /// <inheritdoc />
    public async Task PrintExpiryAlertsReportAsync(
        IEnumerable<ExpiryAlertReportItem> alerts,
        ExpiryAlertSummary summary)
    {
        var content = GenerateExpiryAlertsContent(alerts.ToList(), summary);
        await PrintReportAsync(content, "Expiry Alerts Report");
    }

    private string GenerateExpiryAlertsContent(List<ExpiryAlertReportItem> alerts, ExpiryAlertSummary summary)
    {
        var sb = new StringBuilder();

        // Header
        sb.AppendLine(new string('=', LineWidth));
        sb.AppendLine(CenterText("EXPIRY ALERTS REPORT", LineWidth));
        sb.AppendLine(new string('=', LineWidth));

        // Report Info
        sb.AppendLine($"Generated: {summary.GeneratedAt.ToLocalTime():yyyy-MM-dd HH:mm}");
        if (!string.IsNullOrEmpty(summary.GeneratedBy))
        {
            sb.AppendLine($"Generated by: {summary.GeneratedBy}");
        }
        sb.AppendLine(new string('-', LineWidth));

        // Alert Summary
        sb.AppendLine("ALERT SUMMARY");
        sb.AppendLine(new string('-', LineWidth));
        sb.AppendLine(FormatLine("EXPIRED:", $"{summary.ExpiredCount} items"));
        sb.AppendLine(FormatLine("CRITICAL (<=7 days):", $"{summary.CriticalCount} items"));
        sb.AppendLine(FormatLine("WARNING (<=30 days):", $"{summary.WarningCount} items"));
        sb.AppendLine(new string(' ', LineWidth - 20) + new string('-', 20));
        sb.AppendLine(FormatLine("TOTAL ITEMS:", $"{summary.TotalCount}"));
        sb.AppendLine(FormatLine("TOTAL AT-RISK VALUE:", $"KSh {summary.TotalAtRiskValue:N2}"));
        sb.AppendLine(new string('-', LineWidth));

        // Expired Items (highest priority)
        var expiredItems = alerts.Where(a => a.AlertLevel == "Expired").ToList();
        if (expiredItems.Count > 0)
        {
            sb.AppendLine("*** EXPIRED ITEMS ***");
            sb.AppendLine(new string('-', LineWidth));
            foreach (var item in expiredItems.Take(25))
            {
                var name = item.ProductName.Length > 24
                    ? item.ProductName[..21] + "..."
                    : item.ProductName;
                sb.AppendLine($"[EXPIRED] {name}");
                sb.AppendLine($"  Batch: {item.BatchNumber}");
                sb.AppendLine($"  Qty: {item.CurrentQuantity}  Expired: {item.ExpiryDate.ToLocalTime():yyyy-MM-dd}");
                sb.AppendLine($"  Value: KSh {item.TotalValue:N2}");
            }
            if (expiredItems.Count > 25)
            {
                sb.AppendLine($"  ... and {expiredItems.Count - 25} more expired items");
            }
            sb.AppendLine(new string('-', LineWidth));
        }

        // Critical Items
        var criticalItems = alerts.Where(a => a.AlertLevel == "Critical").ToList();
        if (criticalItems.Count > 0)
        {
            sb.AppendLine("*** CRITICAL (Expiring within 7 days) ***");
            sb.AppendLine(new string('-', LineWidth));
            foreach (var item in criticalItems.Take(25))
            {
                var name = item.ProductName.Length > 24
                    ? item.ProductName[..21] + "..."
                    : item.ProductName;
                sb.AppendLine($"[CRITICAL] {name}");
                sb.AppendLine($"  Batch: {item.BatchNumber}");
                sb.AppendLine($"  Qty: {item.CurrentQuantity}  Expires: {item.ExpiryDate.ToLocalTime():yyyy-MM-dd} ({item.DaysUntilExpiry} days)");
                sb.AppendLine($"  Value: KSh {item.TotalValue:N2}");
            }
            if (criticalItems.Count > 25)
            {
                sb.AppendLine($"  ... and {criticalItems.Count - 25} more critical items");
            }
            sb.AppendLine(new string('-', LineWidth));
        }

        // Warning Items
        var warningItems = alerts.Where(a => a.AlertLevel == "Warning").ToList();
        if (warningItems.Count > 0)
        {
            sb.AppendLine("WARNING (Expiring within 30 days)");
            sb.AppendLine(new string('-', LineWidth));
            foreach (var item in warningItems.Take(25))
            {
                var name = item.ProductName.Length > 24
                    ? item.ProductName[..21] + "..."
                    : item.ProductName;
                sb.AppendLine($"[WARNING] {name}");
                sb.AppendLine($"  Batch: {item.BatchNumber}  Qty: {item.CurrentQuantity}");
                sb.AppendLine($"  Expires: {item.ExpiryDate.ToLocalTime():yyyy-MM-dd} ({item.DaysUntilExpiry} days)");
            }
            if (warningItems.Count > 25)
            {
                sb.AppendLine($"  ... and {warningItems.Count - 25} more warning items");
            }
            sb.AppendLine(new string('-', LineWidth));
        }

        // Footer
        sb.AppendLine(new string('=', LineWidth));
        sb.AppendLine(CenterText("** END OF REPORT **", LineWidth));
        sb.AppendLine(CenterText("Action Required: Dispose/Sell Soon", LineWidth));
        sb.AppendLine(new string('=', LineWidth));

        return sb.ToString();
    }

    #endregion
}
