using System.Windows;
using System.Windows.Documents;
using HospitalityPOS.Core.DTOs;

namespace HospitalityPOS.WPF.Views.Dialogs;

/// <summary>
/// Interaction logic for XReportDataDialog.xaml
/// </summary>
public partial class XReportDataDialog : Window
{
    private readonly XReportData _report;
    private readonly bool _autoPrint;

    /// <summary>
    /// Initializes a new instance of the <see cref="XReportDataDialog"/> class.
    /// </summary>
    /// <param name="report">The X-Report data to display.</param>
    /// <param name="autoPrint">If true, automatically prints the report when shown.</param>
    public XReportDataDialog(XReportData report, bool autoPrint = false)
    {
        InitializeComponent();
        _report = report ?? throw new ArgumentNullException(nameof(report));
        _autoPrint = autoPrint;
        PopulateReport();
    }

    private void PopulateReport()
    {
        // Header
        BusinessNameText.Text = _report.BusinessName;
        if (!string.IsNullOrEmpty(_report.BusinessAddress))
        {
            BusinessAddressText.Text = _report.BusinessAddress;
            BusinessAddressText.Visibility = Visibility.Visible;
        }
        if (!string.IsNullOrEmpty(_report.BusinessPhone))
        {
            BusinessPhoneText.Text = $"Phone: {_report.BusinessPhone}";
            BusinessPhoneText.Visibility = Visibility.Visible;
        }

        // Terminal Info
        TerminalInfoText.Text = $"Terminal: {_report.TerminalCode} ({_report.TerminalName})";

        // Report Info
        ReportNumberText.Text = _report.ReportNumber;
        GeneratedAtText.Text = _report.GeneratedAt.ToLocalTime().ToString("yyyy-MM-dd HH:mm");
        GeneratedByText.Text = $"Generated by: {_report.GeneratedByName}";

        // Shift Info
        ShiftStartedText.Text = _report.ShiftStarted.ToLocalTime().ToString("yyyy-MM-dd HH:mm");
        CurrentTimeText.Text = _report.CurrentTime.ToLocalTime().ToString("yyyy-MM-dd HH:mm");
        DurationText.Text = _report.ShiftDurationFormatted;

        // Cashier Sessions
        if (_report.CashierSessions.Count > 0)
        {
            CashierSessionsItems.ItemsSource = _report.CashierSessions;
        }
        else
        {
            NoCashierSessionsText.Visibility = Visibility.Visible;
        }

        // Sales Summary
        GrossSalesText.Text = $"KSh {_report.GrossSales:N2}";
        DiscountsText.Text = $"-KSh {_report.Discounts:N2}";
        RefundsText.Text = $"-KSh {_report.Refunds:N2}";
        NetSalesText.Text = $"KSh {_report.NetSales:N2}";
        TaxText.Text = $"KSh {_report.TaxAmount:N2}";
        TipsText.Text = $"KSh {_report.TipsCollected:N2}";
        GrandTotalText.Text = $"KSh {_report.GrandTotal:N2}";

        // Payment Breakdown by Type
        if (_report.PaymentTypeBreakdown.Count > 0)
        {
            PaymentTypeBreakdownItems.ItemsSource = _report.PaymentTypeBreakdown;
        }
        else if (_report.PaymentBreakdown.Count > 0)
        {
            // Fallback: create type breakdown from flat list
            var typeBreakdown = _report.PaymentBreakdown
                .GroupBy(p => p.PaymentMethodType)
                .Select(g => new PaymentTypeBreakdown
                {
                    PaymentType = g.Key,
                    PaymentTypeName = PaymentTypeBreakdown.GetPaymentTypeName(g.Key),
                    TotalAmount = g.Sum(m => m.Amount),
                    TotalTransactionCount = g.Sum(m => m.TransactionCount),
                    Percentage = _report.TotalPayments > 0
                        ? Math.Round(g.Sum(m => m.Amount) / _report.TotalPayments * 100, 1)
                        : 0,
                    Methods = g.ToList()
                })
                .OrderBy(t => t.PaymentType)
                .ToList();
            PaymentTypeBreakdownItems.ItemsSource = typeBreakdown;
        }
        else
        {
            NoPaymentBreakdownText.Visibility = Visibility.Visible;
        }

        // Statistics
        TransactionCountText.Text = _report.TransactionCount.ToString();
        AverageTransactionText.Text = $"KSh {_report.AverageTransaction:N2}";
        VoidCountText.Text = _report.VoidCount.ToString();
        RefundCountText.Text = _report.RefundCount.ToString();
        DiscountCountText.Text = _report.DiscountCount.ToString();

        // Cash Drawer
        OpeningFloatText.Text = $"KSh {_report.OpeningFloat:N2}";
        CashReceivedText.Text = $"KSh {_report.CashReceived:N2}";
        CashRefundsText.Text = $"-KSh {_report.CashRefunds:N2}";
        CashPayoutsText.Text = $"-KSh {_report.CashPayouts:N2}";
        ExpectedCashText.Text = $"KSh {_report.ExpectedCash:N2}";
    }

    protected override void OnContentRendered(EventArgs e)
    {
        base.OnContentRendered(e);
        if (_autoPrint)
        {
            PrintReport();
        }
    }

    private void PrintButton_Click(object sender, RoutedEventArgs e)
    {
        PrintReport();
    }

    private void PrintReport()
    {
        // Generate print content for 80mm thermal printer (48 chars per line)
        var printContent = GeneratePrintContent();

        // Create a FlowDocument for printing
        var document = new FlowDocument
        {
            FontFamily = new System.Windows.Media.FontFamily("Consolas"),
            FontSize = 10,
            PageWidth = 280, // ~80mm at 96 DPI
            PagePadding = new Thickness(10),
            ColumnWidth = 280
        };

        // Split content into lines and add paragraphs
        var lines = printContent.Split('\n');
        foreach (var line in lines)
        {
            var paragraph = new Paragraph(new Run(line))
            {
                Margin = new Thickness(0, 0, 0, 0),
                LineHeight = 1
            };
            document.Blocks.Add(paragraph);
        }

        // Show print dialog
        var printDialog = new System.Windows.Controls.PrintDialog();
        if (printDialog.ShowDialog() == true)
        {
            var paginator = ((IDocumentPaginatorSource)document).DocumentPaginator;
            printDialog.PrintDocument(paginator, "X Report");
            MessageBox.Show("Report sent to printer.", "Print", MessageBoxButton.OK, MessageBoxImage.Information);
        }
    }

    private string GeneratePrintContent()
    {
        const int lineWidth = 48;
        var sb = new System.Text.StringBuilder();

        // Header separator
        sb.AppendLine(new string('-', lineWidth));

        // Business name (centered)
        sb.AppendLine(CenterText(_report.BusinessName, lineWidth));
        if (!string.IsNullOrEmpty(_report.BusinessAddress))
        {
            sb.AppendLine(CenterText(_report.BusinessAddress, lineWidth));
        }
        if (!string.IsNullOrEmpty(_report.BusinessPhone))
        {
            sb.AppendLine(CenterText($"Phone: {_report.BusinessPhone}", lineWidth));
        }

        sb.AppendLine(new string('-', lineWidth));

        // Report title
        sb.AppendLine(CenterText("X REPORT", lineWidth));
        sb.AppendLine($"Terminal: {_report.TerminalCode}");
        sb.AppendLine($"Date: {_report.GeneratedAt.ToLocalTime():yyyy-MM-dd}");
        sb.AppendLine($"Time: {_report.GeneratedAt.ToLocalTime():HH:mm}");
        sb.AppendLine($"Report #: {_report.ReportNumber}");
        sb.AppendLine($"Generated by: {_report.GeneratedByName}");

        sb.AppendLine(new string('-', lineWidth));

        // Shift Info
        sb.AppendLine("SHIFT INFORMATION");
        sb.AppendLine($"Started: {_report.ShiftStarted.ToLocalTime():yyyy-MM-dd HH:mm}");
        sb.AppendLine($"Duration: {_report.ShiftDurationFormatted}");

        sb.AppendLine(new string('-', lineWidth));

        // Cashier Sessions
        sb.AppendLine("CASHIER SESSIONS");
        if (_report.CashierSessions.Count > 0)
        {
            foreach (var session in _report.CashierSessions)
            {
                sb.AppendLine($"{session.CashierName}");
                sb.AppendLine($"  {session.StartTime.ToLocalTime():HH:mm} - {(session.EndTime?.ToLocalTime().ToString("HH:mm") ?? "Active")}");
                sb.AppendLine(FormatLine($"  Sales ({session.TransactionCount}):", $"KSh {session.SalesTotal:N2}", lineWidth));
            }
        }
        else
        {
            sb.AppendLine("No sessions recorded");
        }

        sb.AppendLine(new string('-', lineWidth));

        // Sales Summary
        sb.AppendLine("SALES SUMMARY");
        sb.AppendLine(FormatLine("Gross Sales:", $"KSh {_report.GrossSales:N2}", lineWidth));
        sb.AppendLine(FormatLine("Discounts:", $"-KSh {_report.Discounts:N2}", lineWidth));
        sb.AppendLine(FormatLine("Refunds:", $"-KSh {_report.Refunds:N2}", lineWidth));
        sb.AppendLine(FormatLine("Net Sales:", $"KSh {_report.NetSales:N2}", lineWidth));
        sb.AppendLine(FormatLine("Tax:", $"KSh {_report.TaxAmount:N2}", lineWidth));
        sb.AppendLine(FormatLine("Tips:", $"KSh {_report.TipsCollected:N2}", lineWidth));
        sb.AppendLine(new string(' ', lineWidth - 16) + new string('-', 16));
        sb.AppendLine(FormatLine("GRAND TOTAL:", $"KSh {_report.GrandTotal:N2}", lineWidth));

        sb.AppendLine(new string('-', lineWidth));

        // Payment Breakdown by Type
        sb.AppendLine("PAYMENT BREAKDOWN");
        var paymentTypes = _report.PaymentTypeBreakdown.Count > 0
            ? _report.PaymentTypeBreakdown
            : _report.PaymentBreakdown
                .GroupBy(p => p.PaymentMethodType)
                .Select(g => new PaymentTypeBreakdown
                {
                    PaymentTypeName = PaymentTypeBreakdown.GetPaymentTypeName(g.Key),
                    TotalAmount = g.Sum(m => m.Amount),
                    TotalTransactionCount = g.Sum(m => m.TransactionCount),
                    Percentage = _report.TotalPayments > 0
                        ? Math.Round(g.Sum(m => m.Amount) / _report.TotalPayments * 100, 1)
                        : 0,
                    Methods = g.ToList()
                })
                .ToList();

        if (paymentTypes.Count > 0)
        {
            foreach (var pt in paymentTypes)
            {
                // Type header
                sb.AppendLine(FormatLine($"[{pt.PaymentTypeName}] ({pt.TotalTransactionCount}):", $"KSh {pt.TotalAmount:N2}", lineWidth));
                // Individual methods within type
                foreach (var pm in pt.Methods)
                {
                    sb.AppendLine(FormatLine($"  {pm.PaymentMethodName} ({pm.TransactionCount}):", $"KSh {pm.Amount:N2}", lineWidth));
                }
            }
        }
        else
        {
            sb.AppendLine("No payments recorded");
        }

        sb.AppendLine(new string('-', lineWidth));

        // Statistics
        sb.AppendLine("STATISTICS");
        sb.AppendLine($"Total Transactions: {_report.TransactionCount}");
        sb.AppendLine($"Average Value: KSh {_report.AverageTransaction:N2}");
        sb.AppendLine($"Voids: {_report.VoidCount}, Refunds: {_report.RefundCount}");

        sb.AppendLine(new string('-', lineWidth));

        // Cash Drawer
        sb.AppendLine("CASH DRAWER");
        sb.AppendLine(FormatLine("Opening Float:", $"KSh {_report.OpeningFloat:N2}", lineWidth));
        sb.AppendLine(FormatLine("Cash Received:", $"KSh {_report.CashReceived:N2}", lineWidth));
        sb.AppendLine(FormatLine("Cash Refunds:", $"-KSh {_report.CashRefunds:N2}", lineWidth));
        sb.AppendLine(FormatLine("Cash Payouts:", $"-KSh {_report.CashPayouts:N2}", lineWidth));
        sb.AppendLine(new string(' ', lineWidth - 16) + new string('-', 16));
        sb.AppendLine(FormatLine("EXPECTED CASH:", $"KSh {_report.ExpectedCash:N2}", lineWidth));

        sb.AppendLine(new string('-', lineWidth));

        // Footer
        sb.AppendLine(CenterText("** END OF X REPORT **", lineWidth));
        sb.AppendLine(CenterText("Mid-shift examination", lineWidth));
        sb.AppendLine(new string('-', lineWidth));

        return sb.ToString();
    }

    private static string CenterText(string text, int width)
    {
        if (text.Length >= width) return text[..width];
        var padding = (width - text.Length) / 2;
        return new string(' ', padding) + text;
    }

    private static string FormatLine(string label, string value, int width)
    {
        var spaces = width - label.Length - value.Length;
        if (spaces < 1) spaces = 1;
        return label + new string(' ', spaces) + value;
    }

    private void CloseButton_Click(object sender, RoutedEventArgs e)
    {
        Close();
    }
}
