using System.Windows;
using System.Windows.Documents;
using HospitalityPOS.Core.Models.Reports;
using OxyPlot;
using OxyPlot.Axes;
using OxyPlot.Series;

namespace HospitalityPOS.WPF.Views.Dialogs;

/// <summary>
/// Interaction logic for XReportDialog.xaml
/// </summary>
public partial class XReportDialog : Window
{
    private readonly XReport _report;

    /// <summary>
    /// Initializes a new instance of the <see cref="XReportDialog"/> class.
    /// </summary>
    /// <param name="report">The X-Report to display.</param>
    public XReportDialog(XReport report)
    {
        InitializeComponent();
        _report = report ?? throw new ArgumentNullException(nameof(report));
        PopulateReport();
    }

    private void PopulateReport()
    {
        // Header
        BusinessNameText.Text = _report.BusinessName;
        if (!string.IsNullOrEmpty(_report.BusinessAddress))
        {
            BusinessAddressText.Text = _report.BusinessAddress;
            BusinessAddressText.Visibility = Visibility.Visible;
        }
        if (!string.IsNullOrEmpty(_report.BusinessPhone))
        {
            BusinessPhoneText.Text = $"Phone: {_report.BusinessPhone}";
            BusinessPhoneText.Visibility = Visibility.Visible;
        }

        // Report Info
        ReportNumberText.Text = $"X-{_report.ReportNumber:D4}";
        GeneratedAtText.Text = _report.GeneratedAt.ToLocalTime().ToString("yyyy-MM-dd HH:mm");
        GeneratedByText.Text = $"Generated by: {_report.GeneratedBy}";

        // Work Period Info
        OpenedAtText.Text = _report.WorkPeriodOpenedAt.ToLocalTime().ToString("yyyy-MM-dd HH:mm");
        OpenedByText.Text = _report.WorkPeriodOpenedBy;
        DurationText.Text = FormatDuration(_report.Duration);

        // Sales Summary
        GrossSalesText.Text = $"KSh {_report.GrossSales:N2}";
        DiscountsText.Text = $"-KSh {_report.TotalDiscounts:N2}";
        NetSalesText.Text = $"KSh {_report.NetSales:N2}";
        TaxText.Text = $"KSh {_report.TaxCollected:N2}";
        GrandTotalText.Text = $"KSh {_report.GrandTotal:N2}";

        // Sales by Category
        if (_report.SalesByCategory.Count > 0)
        {
            CategorySalesItems.ItemsSource = _report.SalesByCategory;
        }
        else
        {
            NoCategorySalesText.Visibility = Visibility.Visible;
        }

        // Sales by Payment Method
        if (_report.SalesByPaymentMethod.Count > 0)
        {
            PaymentMethodItems.ItemsSource = _report.SalesByPaymentMethod;
        }
        else
        {
            NoPaymentSalesText.Visibility = Visibility.Visible;
        }

        // Sales by User
        if (_report.SalesByUser.Count > 0)
        {
            UserSalesItems.ItemsSource = _report.SalesByUser;
        }
        else
        {
            NoUserSalesText.Visibility = Visibility.Visible;
        }

        // Hourly Sales Chart
        SetupHourlySalesChart();

        // Transaction Statistics
        TransactionCountText.Text = _report.TransactionCount.ToString();
        AverageValueText.Text = $"KSh {_report.AverageTransactionValue:N2}";

        // Voids
        VoidCountRun.Text = _report.VoidCount.ToString();
        if (_report.Voids.Count > 0)
        {
            VoidsItems.ItemsSource = _report.Voids;
            VoidTotalGrid.Visibility = Visibility.Visible;
            VoidTotalText.Text = $"KSh {_report.VoidTotal:N2}";
        }
        else
        {
            NoVoidsText.Visibility = Visibility.Visible;
        }

        // Cash Position
        OpeningFloatText.Text = $"KSh {_report.OpeningFloat:N2}";
        ExpectedCashText.Text = $"KSh {_report.ExpectedCash:N2}";
    }

    private static string FormatDuration(TimeSpan duration)
    {
        var hours = (int)duration.TotalHours;
        var minutes = duration.Minutes;
        return $"{hours}h {minutes:D2}m";
    }

    private void SetupHourlySalesChart()
    {
        if (_report.HourlySales == null || _report.HourlySales.Count == 0)
        {
            NoHourlySalesText.Visibility = Visibility.Visible;
            HourlySalesChart.Visibility = Visibility.Collapsed;
            return;
        }

        // Check if there's any actual sales data
        var hasData = _report.HourlySales.Any(h => h.TotalAmount > 0);
        if (!hasData)
        {
            NoHourlySalesText.Visibility = Visibility.Visible;
            HourlySalesChart.Visibility = Visibility.Collapsed;
            return;
        }

        var model = new PlotModel
        {
            Background = OxyColors.Transparent,
            PlotAreaBorderColor = OxyColor.FromRgb(74, 74, 106), // #4A4A6A
            TextColor = OxyColor.FromRgb(136, 136, 170), // #8888AA
        };

        // X-axis: Hours
        var categoryAxis = new CategoryAxis
        {
            Position = AxisPosition.Bottom,
            Key = "Hours",
            TickStyle = OxyPlot.Axes.TickStyle.None,
            MajorGridlineStyle = LineStyle.None,
            TextColor = OxyColor.FromRgb(136, 136, 170),
            AxislineColor = OxyColor.FromRgb(74, 74, 106),
            GapWidth = 0.2
        };

        // Only show labels for hours with sales or key hours
        foreach (var hourData in _report.HourlySales)
        {
            var label = hourData.Hour % 3 == 0 ? hourData.HourLabel.Replace(" AM", "a").Replace(" PM", "p") : "";
            categoryAxis.Labels.Add(label);
        }

        model.Axes.Add(categoryAxis);

        // Y-axis: Amount
        var valueAxis = new LinearAxis
        {
            Position = AxisPosition.Left,
            Minimum = 0,
            TickStyle = OxyPlot.Axes.TickStyle.None,
            MajorGridlineStyle = LineStyle.Solid,
            MajorGridlineColor = OxyColor.FromRgb(61, 61, 92), // #3D3D5C
            TextColor = OxyColor.FromRgb(136, 136, 170),
            AxislineColor = OxyColor.FromRgb(74, 74, 106),
            StringFormat = "KSh #,0"
        };
        model.Axes.Add(valueAxis);

        // Bar series for sales
        var barSeries = new BarSeries
        {
            FillColor = OxyColor.FromRgb(76, 175, 80), // #4CAF50
            StrokeColor = OxyColor.FromRgb(56, 142, 60),
            StrokeThickness = 1,
            BarWidth = 0.8
        };

        foreach (var hourData in _report.HourlySales)
        {
            barSeries.Items.Add(new BarItem { Value = (double)hourData.TotalAmount });
        }

        model.Series.Add(barSeries);

        HourlySalesChart.Model = model;
    }

    private void PrintButton_Click(object sender, RoutedEventArgs e)
    {
        // Generate print content for 80mm thermal printer (48 chars per line)
        var printContent = GeneratePrintContent();

        // Create a FlowDocument for printing
        var document = new FlowDocument
        {
            FontFamily = new System.Windows.Media.FontFamily("Consolas"),
            FontSize = 10,
            PageWidth = 280, // ~80mm at 96 DPI
            PagePadding = new Thickness(10),
            ColumnWidth = 280
        };

        // Split content into lines and add paragraphs
        var lines = printContent.Split('\n');
        foreach (var line in lines)
        {
            var paragraph = new Paragraph(new Run(line))
            {
                Margin = new Thickness(0, 0, 0, 0),
                LineHeight = 1
            };
            document.Blocks.Add(paragraph);
        }

        // Show print dialog
        var printDialog = new System.Windows.Controls.PrintDialog();
        if (printDialog.ShowDialog() == true)
        {
            var paginator = ((IDocumentPaginatorSource)document).DocumentPaginator;
            printDialog.PrintDocument(paginator, "X Report");
            MessageBox.Show("Report sent to printer.", "Print", MessageBoxButton.OK, MessageBoxImage.Information);
        }
    }

    private string GeneratePrintContent()
    {
        const int lineWidth = 48;
        var sb = new System.Text.StringBuilder();

        // Header separator
        sb.AppendLine(new string('-', lineWidth));

        // Business name (centered)
        sb.AppendLine(CenterText(_report.BusinessName, lineWidth));
        if (!string.IsNullOrEmpty(_report.BusinessAddress))
        {
            sb.AppendLine(CenterText(_report.BusinessAddress, lineWidth));
        }
        if (!string.IsNullOrEmpty(_report.BusinessPhone))
        {
            sb.AppendLine(CenterText($"Phone: {_report.BusinessPhone}", lineWidth));
        }

        sb.AppendLine(new string('-', lineWidth));

        // Report title
        sb.AppendLine("X REPORT");
        sb.AppendLine($"Date: {_report.GeneratedAt.ToLocalTime():yyyy-MM-dd}        Time: {_report.GeneratedAt.ToLocalTime():HH:mm}");
        sb.AppendLine($"Report #: X-{_report.ReportNumber:D4}");
        sb.AppendLine($"Generated by: {_report.GeneratedBy}");

        sb.AppendLine(new string('-', lineWidth));

        // Work Period
        sb.AppendLine("WORK PERIOD");
        sb.AppendLine($"Opened: {_report.WorkPeriodOpenedAt.ToLocalTime():yyyy-MM-dd HH:mm} by {_report.WorkPeriodOpenedBy}");
        sb.AppendLine($"Duration: {FormatDuration(_report.Duration)}");

        sb.AppendLine(new string('-', lineWidth));

        // Sales Summary
        sb.AppendLine("SALES SUMMARY");
        sb.AppendLine(FormatLine("Gross Sales:", $"KSh {_report.GrossSales:N2}", lineWidth));
        sb.AppendLine(FormatLine("Discounts:", $"-KSh {_report.TotalDiscounts:N2}", lineWidth));
        sb.AppendLine(FormatLine("Net Sales:", $"KSh {_report.NetSales:N2}", lineWidth));
        sb.AppendLine(FormatLine("Tax:", $"KSh {_report.TaxCollected:N2}", lineWidth));
        sb.AppendLine(new string(' ', lineWidth - 16) + new string('-', 16));
        sb.AppendLine(FormatLine("GRAND TOTAL:", $"KSh {_report.GrandTotal:N2}", lineWidth));

        sb.AppendLine(new string('-', lineWidth));

        // Sales by Category
        sb.AppendLine("SALES BY CATEGORY");
        if (_report.SalesByCategory.Count > 0)
        {
            foreach (var cat in _report.SalesByCategory)
            {
                sb.AppendLine(FormatLine($"{cat.CategoryName} ({cat.ItemCount}):", $"KSh {cat.TotalAmount:N2}", lineWidth));
            }
        }
        else
        {
            sb.AppendLine("No sales recorded");
        }

        sb.AppendLine(new string('-', lineWidth));

        // Sales by Payment Method
        sb.AppendLine("SALES BY PAYMENT METHOD");
        if (_report.SalesByPaymentMethod.Count > 0)
        {
            foreach (var pm in _report.SalesByPaymentMethod)
            {
                sb.AppendLine(FormatLine($"{pm.PaymentMethod} ({pm.TransactionCount}):", $"KSh {pm.TotalAmount:N2}", lineWidth));
            }
        }
        else
        {
            sb.AppendLine("No payments recorded");
        }

        sb.AppendLine(new string('-', lineWidth));

        // Sales by Cashier
        sb.AppendLine("SALES BY CASHIER");
        if (_report.SalesByUser.Count > 0)
        {
            foreach (var user in _report.SalesByUser)
            {
                sb.AppendLine(FormatLine($"{user.UserName} ({user.TransactionCount}):", $"KSh {user.TotalAmount:N2}", lineWidth));
            }
        }
        else
        {
            sb.AppendLine("No sales by user recorded");
        }

        sb.AppendLine(new string('-', lineWidth));

        // Transaction Statistics
        sb.AppendLine("TRANSACTION STATISTICS");
        sb.AppendLine($"Total Transactions: {_report.TransactionCount}");
        sb.AppendLine($"Average Value: KSh {_report.AverageTransactionValue:N2}");

        sb.AppendLine(new string('-', lineWidth));

        // Voids
        sb.AppendLine($"VOIDS ({_report.VoidCount})");
        if (_report.Voids.Count > 0)
        {
            foreach (var v in _report.Voids)
            {
                sb.AppendLine($"#{v.ReceiptNumber}: KSh {v.Amount:N2}");
                if (!string.IsNullOrEmpty(v.Reason))
                {
                    var reason = v.Reason.Length > lineWidth - 2 ? v.Reason[..(lineWidth - 5)] + "..." : v.Reason;
                    sb.AppendLine($"  {reason}");
                }
            }
            sb.AppendLine(FormatLine("Void Total:", $"KSh {_report.VoidTotal:N2}", lineWidth));
        }
        else
        {
            sb.AppendLine("No voids recorded");
        }

        sb.AppendLine(new string('-', lineWidth));

        // Cash Position
        sb.AppendLine("CASH POSITION");
        sb.AppendLine(FormatLine("Opening Float:", $"KSh {_report.OpeningFloat:N2}", lineWidth));
        sb.AppendLine(FormatLine("Expected Cash:", $"KSh {_report.ExpectedCash:N2}", lineWidth));

        sb.AppendLine(new string('-', lineWidth));

        // Footer
        sb.AppendLine(CenterText("** END OF X REPORT **", lineWidth));
        sb.AppendLine(new string('-', lineWidth));

        return sb.ToString();
    }

    private static string CenterText(string text, int width)
    {
        if (text.Length >= width) return text[..width];
        var padding = (width - text.Length) / 2;
        return new string(' ', padding) + text;
    }

    private static string FormatLine(string label, string value, int width)
    {
        var spaces = width - label.Length - value.Length;
        if (spaces < 1) spaces = 1;
        return label + new string(' ', spaces) + value;
    }

    private void CloseButton_Click(object sender, RoutedEventArgs e)
    {
        Close();
    }
}
