using HospitalityPOS.Core.Enums;

namespace HospitalityPOS.Core.Entities;

/// <summary>
/// Represents a journal entry in the accounting system.
/// </summary>
public class JournalEntry : BaseEntity
{
    /// <summary>
    /// Entry number (e.g., JE-20240101-0001).
    /// </summary>
    public string EntryNumber { get; set; } = string.Empty;

    /// <summary>
    /// Date of the entry (posting date).
    /// </summary>
    public DateTime EntryDate { get; set; }

    /// <summary>
    /// Description/memo for the entry.
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Reference type (e.g., "Sale", "Purchase", "Expense").
    /// </summary>
    public string? ReferenceType { get; set; }

    /// <summary>
    /// Reference ID for linking to source document.
    /// </summary>
    public int? ReferenceId { get; set; }

    /// <summary>
    /// Source transaction type for automated entries.
    /// </summary>
    public TransactionSourceType? SourceType { get; set; }

    /// <summary>
    /// Accounting period this entry belongs to.
    /// </summary>
    public int? AccountingPeriodId { get; set; }

    /// <summary>
    /// Entry status.
    /// </summary>
    public JournalEntryStatus Status { get; set; } = JournalEntryStatus.Posted;

    /// <summary>
    /// Whether the entry has been posted.
    /// </summary>
    public bool IsPosted { get; set; }

    /// <summary>
    /// Posted date/time.
    /// </summary>
    public DateTime? PostedAt { get; set; }

    /// <summary>
    /// User who posted the entry.
    /// </summary>
    public int? PostedByUserId { get; set; }

    /// <summary>
    /// Whether this is an auto-generated entry.
    /// </summary>
    public bool IsAutoGenerated { get; set; }

    /// <summary>
    /// Whether this is a reversing entry.
    /// </summary>
    public bool IsReversing { get; set; }

    /// <summary>
    /// ID of the original entry if this is a reversal.
    /// </summary>
    public int? ReversesEntryId { get; set; }

    /// <summary>
    /// ID of the reversal entry if this entry has been reversed.
    /// </summary>
    public int? ReversedByEntryId { get; set; }

    /// <summary>
    /// Whether this is a closing entry.
    /// </summary>
    public bool IsClosingEntry { get; set; }

    /// <summary>
    /// Whether this is an adjusting entry.
    /// </summary>
    public bool IsAdjusting { get; set; }

    /// <summary>
    /// Total debit amount (calculated).
    /// </summary>
    public decimal TotalDebits { get; set; }

    /// <summary>
    /// Total credit amount (calculated).
    /// </summary>
    public decimal TotalCredits { get; set; }

    /// <summary>
    /// Store ID if store-specific.
    /// </summary>
    public int? StoreId { get; set; }

    /// <summary>
    /// Currency code.
    /// </summary>
    public string CurrencyCode { get; set; } = "KES";

    /// <summary>
    /// Exchange rate if foreign currency.
    /// </summary>
    public decimal ExchangeRate { get; set; } = 1;

    /// <summary>
    /// Approval status for entries requiring approval.
    /// </summary>
    public bool? IsApproved { get; set; }

    /// <summary>
    /// User who approved the entry.
    /// </summary>
    public int? ApprovedByUserId { get; set; }

    /// <summary>
    /// Approval date.
    /// </summary>
    public DateTime? ApprovedAt { get; set; }

    /// <summary>
    /// Notes/attachments.
    /// </summary>
    public string? Notes { get; set; }

    /// <summary>
    /// Attachment file paths (JSON array).
    /// </summary>
    public string? Attachments { get; set; }

    // Navigation properties
    public virtual AccountingPeriod? AccountingPeriod { get; set; }
    public virtual User? CreatedByUser { get; set; }
    public virtual User? PostedByUser { get; set; }
    public virtual User? ApprovedByUser { get; set; }
    public virtual JournalEntry? ReversesEntry { get; set; }
    public virtual JournalEntry? ReversedByEntry { get; set; }
    public virtual Store? Store { get; set; }
    public virtual ICollection<JournalEntryLine> JournalEntryLines { get; set; } = new List<JournalEntryLine>();

    /// <summary>
    /// Validates that the entry balances (debits = credits).
    /// </summary>
    public bool IsBalanced => Math.Abs(TotalDebits - TotalCredits) < 0.01m;

    /// <summary>
    /// Recalculates totals from lines.
    /// </summary>
    public void RecalculateTotals()
    {
        TotalDebits = JournalEntryLines.Sum(l => l.DebitAmount);
        TotalCredits = JournalEntryLines.Sum(l => l.CreditAmount);
    }
}
