using HospitalityPOS.Core.Enums;

namespace HospitalityPOS.Core.Entities;

/// <summary>
/// Represents a purchase order to a supplier.
/// </summary>
public class PurchaseOrder : BaseEntity
{
    /// <summary>
    /// Gets or sets the PO number (e.g., PO-20240101-0001).
    /// </summary>
    public string PONumber { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the supplier ID.
    /// </summary>
    public int SupplierId { get; set; }

    /// <summary>
    /// Gets or sets the order date.
    /// </summary>
    public DateTime OrderDate { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Gets or sets the expected delivery date.
    /// </summary>
    public DateTime? ExpectedDate { get; set; }

    /// <summary>
    /// Gets or sets the PO status.
    /// </summary>
    public PurchaseOrderStatus Status { get; set; } = PurchaseOrderStatus.Draft;

    /// <summary>
    /// Gets or sets the subtotal amount (before tax).
    /// </summary>
    public decimal SubTotal { get; set; }

    /// <summary>
    /// Gets or sets the tax amount.
    /// </summary>
    public decimal TaxAmount { get; set; }

    /// <summary>
    /// Gets or sets the total amount (including tax).
    /// </summary>
    public decimal TotalAmount { get; set; }

    /// <summary>
    /// Gets or sets the payment status.
    /// </summary>
    public PaymentStatus PaymentStatus { get; set; } = PaymentStatus.Unpaid;

    /// <summary>
    /// Gets or sets the amount paid.
    /// </summary>
    public decimal AmountPaid { get; set; }

    /// <summary>
    /// Gets or sets the payment due date.
    /// </summary>
    public DateTime? DueDate { get; set; }

    /// <summary>
    /// Gets or sets the date when fully paid.
    /// </summary>
    public DateTime? PaidDate { get; set; }

    /// <summary>
    /// Gets or sets the supplier invoice number.
    /// </summary>
    public string? InvoiceNumber { get; set; }

    /// <summary>
    /// Gets or sets the ID of the user who created the PO.
    /// </summary>
    public new int CreatedByUserId { get; set; }

    /// <summary>
    /// Gets or sets the date when goods were received.
    /// </summary>
    public DateTime? ReceivedAt { get; set; }

    /// <summary>
    /// Gets or sets additional notes for the PO.
    /// </summary>
    public string? Notes { get; set; }

    /// <summary>
    /// Gets or sets the store ID.
    /// </summary>
    public int? StoreId { get; set; }

    /// <summary>
    /// Gets or sets whether this PO is soft-deleted.
    /// </summary>
    public bool IsDeleted { get; set; }

    /// <summary>
    /// Gets or sets when the PO was deleted.
    /// </summary>
    public DateTime? DeletedAt { get; set; }

    /// <summary>
    /// Gets or sets the user who deleted the PO.
    /// </summary>
    public int? DeletedByUserId { get; set; }

    /// <summary>
    /// Gets or sets the reason for deletion.
    /// </summary>
    public string? DeletionReason { get; set; }

    /// <summary>
    /// Gets or sets when the PO was archived.
    /// </summary>
    public DateTime? ArchivedAt { get; set; }

    /// <summary>
    /// Gets or sets the user who archived the PO.
    /// </summary>
    public int? ArchivedByUserId { get; set; }

    /// <summary>
    /// Gets or sets the reason for archiving.
    /// </summary>
    public string? ArchiveReason { get; set; }

    /// <summary>
    /// Gets or sets whether this PO was auto-generated.
    /// </summary>
    public bool IsAutoGenerated { get; set; }

    /// <summary>
    /// Gets or sets the generation reason (for auto-generated POs).
    /// </summary>
    public string? GenerationReason { get; set; }

    /// <summary>
    /// Gets or sets the priority for review (Critical, High, Medium, Low).
    /// </summary>
    public string? Priority { get; set; }

    // Navigation properties
    public virtual Store? Store { get; set; }
    public virtual Supplier Supplier { get; set; } = null!;
    public virtual User CreatedByUser { get; set; } = null!;
    public virtual ICollection<PurchaseOrderItem> PurchaseOrderItems { get; set; } = new List<PurchaseOrderItem>();
    public virtual ICollection<GoodsReceivedNote> GoodsReceivedNotes { get; set; } = new List<GoodsReceivedNote>();
    public virtual ICollection<SupplierInvoice> SupplierInvoices { get; set; } = new List<SupplierInvoice>();
}
