// <auto-generated />
using System;
using HospitalityPOS.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HospitalityPOS.Infrastructure.Migrations
{
    [DbContext(typeof(POSDbContext))]
    [Migration("20260116000001_AddEtimsEntities")]
    partial class AddEtimsEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Note: This is a partial model snapshot for the eTIMS entities only.
            // A full migration requires regeneration with dotnet ef migrations add command.
            // This migration file is provided for reference and can be applied manually.

            modelBuilder.Entity("HospitalityPOS.Core.Entities.EtimsDevice", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("ApiBaseUrl")
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<string>("ApiKey")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<string>("ApiSecret")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<string>("BranchCode")
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnType("nvarchar(10)");

                b.Property<string>("BranchName")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("BusinessName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("BusinessPin")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<string>("ControlUnitId")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("datetime2")
                    .HasDefaultValueSql("GETUTCDATE()");

                b.Property<int?>("CreatedByUserId")
                    .HasColumnType("int");

                b.Property<string>("DeviceSerialNumber")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Environment")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)")
                    .HasDefaultValue("Sandbox");

                b.Property<bool>("IsActive")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bit")
                    .HasDefaultValue(true);

                b.Property<bool>("IsPrimary")
                    .HasColumnType("bit");

                b.Property<DateTime?>("LastCommunication")
                    .HasColumnType("datetime2");

                b.Property<int>("LastCreditNoteNumber")
                    .HasColumnType("int");

                b.Property<int>("LastInvoiceNumber")
                    .HasColumnType("int");

                b.Property<DateTime?>("RegistrationDate")
                    .HasColumnType("datetime2");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.Property<int?>("UpdatedByUserId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("ControlUnitId")
                    .IsUnique();

                b.HasIndex("DeviceSerialNumber")
                    .IsUnique();

                b.HasIndex("IsPrimary");

                b.ToTable("EtimsDevices", (string)null);
            });
#pragma warning restore 612, 618
        }
    }
}
